export const routes = {
  LANDING: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  HOME: "/home",
  PRODUCTS: "/products",
  DASHBOARD: "/dashboard",
  ADMIN: "/admin/dashboard",
  ADMIN_USERS: "/admin/users",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_ORDERS: "/admin/orders",
  ADMIN_VENDORS: "/admin/vendors",
  ADMIN_APPROVALS: "/admin/approvals",
  ADMIN_SETTINGS: "/admin/settings",
  SUPER_ADMIN: "/super-admin/dashboard",
  DELIVERY: "/delivery/dashboard",
  CREDIT: "/credit",
  CHECKOUT: "/checkout",
  ORDERS: "/orders",
};