import express from 'express';
import authRoutes from '../modules/auth/auth.routes.js';
import userRoutes from '../modules/user/user.routes.js';
import companyRoutes from '../modules/company/company.routes.js';
import vendorRoutes from '../modules/vendor/vendor.routes.js';
import categoryRoutes from '../modules/category/category.routes.js';
import productRoutes from '../modules/product/product.routes.js';
import cartRoutes from '../modules/cart/cart.routes.js';
import orderRoutes from '../modules/order/order.routes.js';
import paymentRoutes from '../modules/payment/payment.routes.js';
import invoiceRoutes from '../modules/invoice/invoice.routes.js';
import notificationRoutes from '../modules/notification/notification.routes.js';
import analyticsRoutes from '../modules/analytics/analytics.routes.js';
import warehouseRoutes from '../modules/warehouse/warehouse.routes.js';
import inventoryRoutes from '../modules/inventory/inventory.routes.js';
import shipmentRoutes from '../modules/shipment/shipment.routes.js';
import pricingRoutes from '../modules/pricing/pricing.routes.js';
import promotionRoutes from '../modules/promotion/promotion.routes.js';
import settingsRoutes from '../modules/settings/settings.routes.js';

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/users', userRoutes);
router.use('/companies', companyRoutes);
router.use('/vendors', vendorRoutes);
router.use('/categories', categoryRoutes);
router.use('/products', productRoutes);
router.use('/cart', cartRoutes);
router.use('/orders', orderRoutes);
router.use('/payments', paymentRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/notifications', notificationRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/warehouses', warehouseRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/shipments', shipmentRoutes);
router.use('/pricing', pricingRoutes);
router.use('/promotions', promotionRoutes);
router.use('/settings', settingsRoutes);

export default router;