export const PERMISSIONS = {
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_PRODUCTS: 'MANAGE_PRODUCTS',
  MANAGE_ORDERS: 'MANAGE_ORDERS',
  MANAGE_PAYMENTS: 'MANAGE_PAYMENTS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
};